config/routes.rb
# frozen_string_literal: true

# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
# Defines the root path route ("/")
# root "articles#index"

Rails.application.routes.draw do
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  get 'sessions/new'
  resources :users
  resources :sessions
  # root "main#index"
  root 'articles#index'
  get '/about-us', to: 'about#index', as: :about # get "/about", to: "about#index"

  # get "/articles", to: "articles#index"
  # get "/articles/:id", to: "articles#show"
  resources :articles do
    resources :comments
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
# frozen_string_literal: true

class Article < ApplicationRecord
  include Visible

  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  include Visible
  belongs_to :article

  validates :commenter, presence: true
  validates :body, presence: true
end

app/models/concerns/visible.rb
# frozen_string_literal: true

module Visible
  extend ActiveSupport::Concern

  VALID_STATUSES = %w[public private archived].freeze

  included do
    validates :status, inclusion: { in: VALID_STATUSES }
  end

  class_methods do
    def public_count
      where(status: 'public').count
    end

    def private_count
      where(status: 'private').count
    end

    def archived_count
      where(status: 'archived').count
    end
  end

  def archived?
    status == 'archived'
  end
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/user.rb
require 'bcrypt'

class User < ApplicationRecord
  # validates :username, presence: true, uniqueness: true, length: {in: 3..20}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }

  validates :password, confirmation: true

  include BCrypt

  def password
    @password ||= Password.new(password_digest)
  end

  def password=(new_password)
    @password = Password.create(new_password)
    self.password_digest = @password
  end
end

app/controllers/about_controller.rb
# frozen_string_literal: true

class AboutController < ApplicationController
  def index; end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

class ArticlesController < ApplicationController
  http_basic_authenticate_with name: 'bikash', password: 'admin', except: %i[index show]
  before_action :set_params, except: %i[index new create]

  def index
    @articles = Article.all
  end

  def show; end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article.destroy
    redirect_to root_path, status: :see_other
  end

  private

  def set_params
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :body, :status)
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def authorize
    redirect_to login_path, alert: 'Not authorized' if current_user.nil?
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  http_basic_authenticate_with name: 'bikash', password: 'admin', only: :destroy

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    # @comment.save
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to articles_path(@article)
  end

  private

  def comment_params
    params.require(:comment).permit(:commenter, :body, :status)
  end
end

app/controllers/main_controller.rb
# frozen_string_literal: true

class MainController < ApplicationController
  def index
    flash[:notice] = 'loggedin successfully'
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by_email(params[:email])
    if user && user.password == params[:password]
      session[:user_id] = user.id
      redirect_to root_path, notice: 'Logged in!'
    else
      flash.now.alert = 'Email or password is invalid'
      render 'new', notice: 'Logged in!'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'Logged out!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save!
      session[:user_id] = @user.id
      redirect_to root_path, notice: 'Thank you for signing up!'
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/articles_helper.rb
# frozen_string_literal: true

module ArticlesHelper
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/about/index.html.erb
<h1>This is about page</h1>

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
  <div>
    <div><%= form.label :title%></div>
    <%= form.text_field :title%>
    <div class="text-danger text-error">
      <% article.errors.full_messages_for(:title).each do |message|%> 
        <%= message%> 
      <% end%>
    </div>
  </div>
  <div>
    <div> <%= form.label :body%></div>
    <%= form.text_area :body%>
    <div class="text-danger text-error">
      <% article.errors.full_messages_for(:body).each do |message|%>
        <div><%= message%></div>
      <%end%>
    </div>
  </div>

  <div>
    <%= form.label :status%>
    <%= form.select :status, ["private", "public", "archived"], selected: "public"%> 
  </div>
  <br/>
  <div><%= form.submit %></div>
<%end%>

app/views/articles/edit.html.erb
<h2>Edit Article</h2>

<%= render "form", article: @article%>

app/views/articles/index.html.erb
<div>&nbsp;</div>

<% if current_user %>
  Logged in as <%= current_user.email %>.
  <%= link_to "Log Out", logout_path %>
<% else %>
  <%= link_to "Sign Up", signup_path %> or
  <%= link_to "Log In", login_path %>
<% end %>

<div class="d-flex align-items-center justify-content-between">
  <h1>Articles</h1>
  <%= link_to "New Article", new_article_path, class: "btn btn-primary"%>
</div>

<section>
  <h6>Our blog has <%= Article.public_count%> public , <%= Article.private_count%> private, and <%=Article.archived_count%> archived articles.</h6>
  <% @articles.each do |article|%>
    <div class="d-flex py-1">
      <div class="flex-grow-1">
        <%= link_to article.title, article%>
        <span class="badge bg-primary"><%= article.status%></span>
      </div>
      <%= link_to "Edit", edit_article_path(article), class: "btn btn-sm btn-secondary"%>
      <span>&nbsp;</span>
      <%= link_to "Delete", article_path(article), data: {
        turbo_method: :delete, 
        turbo_confirm: "Are you sure?"
      }, class: "btn btn-sm btn-danger"%>
    </div>
  <% end %>
</section>

app/views/articles/new.html.erb
<h2>New Article</h2>

<%= form_with model: @article do |form|%>
  <div>
    <div><%= form.label :title%></div>
    <%= form.text_field :title%>
    <div class="text-red">
      <% @article.errors.full_messages_for(:title).each do |message|%> 
        <%= message%> 
      <% end%>
    </div>
  </div>
  <div>
    <div> <%= form.label :body%></div>
    <%= form.text_area :body%>
    <div class="text-red">
      <% @article.errors.full_messages_for(:body).each do |message|%><%= message%><%end%>
    </div>
  </div>

  <div><%= form.submit %></div>
<%end%>

app/views/articles/show.html.erb
<main class="container py-5">
  <h2><%= @article.title %></h2>
  <p> <%= @article.body%></p>

  <%= render "comments/comment", comments: @article.comments%>
  
  <%= render "comments/form"%>
</main>

app/views/comments/_comment.html.erb
<section class="comments">
  <hr/>
  <h5>Comments</h5>
  <% if comments.empty?%>
    <p>no comments yet</p>
  <% else%>
    <%comments.each do |comment|%>
    <div><strong>Commenter: </strong><%= comment.commenter%></div>
    <div><%= comment.body %></div>
    <%= link_to "Delete", [comment.article, comment], data: {
      turbo_method: :delete,
      turbo_confirm: "Are you sure?"
    }%>
    <%end%>
  <% end %>
</section>

app/views/comments/_form.html.erb
 <section class="add-comment">
  <hr/>
  <h4>Add Comment:</h4>
  <%= form_with model: [@article, @article.comments.build ] do |form|%>
    <div>
      <div><%= form.label :commenter%></div>
      <div><%= form.text_field :commenter%></div>
      <div><%= form.label :body%></div>
      <div><%= form.text_area :body %>
      <div><%= form.label :status%> <%=form.select :status, ["private", "public", "archived"], selected: "public"%></div>
    </div>
     
    <div><%= form.submit%></div>
  <% end %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%# <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous"> %>

    <%# <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script> %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render partial: "shared/navbar"%>
    <div class="container">
      <%= render partial: "shared/flash_message" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/main/index.html.erb
<h1>Home page</h1>

app/views/shared/_flash_message.html.erb
<% if flash[:notice]%>
  <div class="alert alert-success" role="alert">
    <%= flash[:notice]%>
  </div>
<% elsif flash[:alert]%>
  <div class="alert alert-danger" role="alert">
    <%= flash[:alert]%>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    <%= link_to "MyApp", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", root_path, class:"nav-link active"%>
        </li>
        <li class="nav-item">
          <%= link_to "About", about_path, class:"nav-link"%>
          <%# <a class="nav-link" href="/about">About</a> %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit "Sign Up" %></div>
<% end %>